apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/nginx_access.log
      tag s3.nginx_access
      format ltsv
      pos_file /var/log/td-agent/nginx_access.log.pos
    </source>
    
    <source>
      @type tail
      path /var/log/nginx_error.log
      tag s3.nginx_error
      pos_file /var/log/td-agent/nginx_error.log.pos
      format /^(?<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?<log_level>\w+)\] (?<pid>\d+).(?<tid>\d+): (?<message>.*)$/
    </source>

    <match s3.nginx_access>
      @type s3
      aws_key_id "#{ENV['AWS_ACCESS_KEY_ID']}"
      aws_sec_key "#{ENV['AWS_SECRET_ACCESS_KEY']}"
      s3_bucket "webtools-private"
      s3_endpoint "https://ax0w66dqmxlm.compat.objectstorage.ap-osaka-1.oraclecloud.com"
      force_path_style true
      time_slice_format %Y/%m/%d/%H%M
      path fluentd_logs/nginx_access/
      s3_object_key_format %{path}%{time_slice}_%{uuid_flush}.%{file_extension}
    </match>
    
    <match s3.nginx_error>
      @type s3
      aws_key_id "#{ENV['AWS_ACCESS_KEY_ID']}"
      aws_sec_key "#{ENV['AWS_SECRET_ACCESS_KEY']}"
      s3_bucket "webtools-private"
      s3_endpoint "https://ax0w66dqmxlm.compat.objectstorage.ap-osaka-1.oraclecloud.com"
      force_path_style true
      time_slice_format %Y/%m/%d/%H%M
      path fluentd_logs/nginx_error/
      s3_object_key_format %{path}%{time_slice}_%{uuid_flush}.%{file_extension}
    </match>
    
    <match **>
      type stdout
    </match>
