apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-proxy-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: log-volume
          mountPath: /var/log
        readinessProbe:
          httpGet:
            path: /_chk
            port: 80
          failureThreshold: 1
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 1
          periodSeconds: 10
      - name: fluentd
        image: nanananakam/fluentd-s3
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: object-storage-s3-write-auth
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: log-volume
          mountPath: /var/log
      volumes:
      - name: nginx-proxy-config
        configMap:
          name: nginx-proxy-config
      - name: fluentd-config
        configMap:
          name: fluentd-config
      - name: log-volume
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nginx
              topologyKey: kubernetes.io/hostname