apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
data:
  nginx.conf: |-
    user  nginx;

    worker_processes 1;
    
    error_log  /var/log/nginx_error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }
    
    http {
        include       /etc/nginx/mime.types;

        server_tokens off;

        log_format  ltsv  'host:$remote_addr\t'
                  'vhost:$http_host\t'
                  'port:$server_port\t'
                  'time:$time_iso8601\t'
                  'method:$request_method\t'
                  'uri:$request_uri\t'
                  'protocol:$server_protocol\t'
                  'status:$status\t'
                  'size:$body_bytes_sent\t'
                  'ua:$http_user_agent\t'
                  'up_subno:$http_x_up_subno\t'
                  'referer:$http_referer\t'
                  'forwardedfor:$http_x_forwarded_for\t'
                  'forwardedproto:$http_x_forwarded_proto\t'
                  'apptime:$upstream_response_time\t'
                  'resptime:$request_time\t'
                  'upstream_addr:$upstream_addr\t'
                  'upstream_status:$upstream_status\t'
                  'upstream_size:$upstream_response_length\t'
                  'cf_ipcountry:$http_cf_ipcountry\t'
                  'cf_ray:$http_cf_ray';

        access_log  /var/log/nginx_access.log ltsv;
        keepalive_timeout  300;

        upstream webtools-front {
            server webtools-front:3000;
        }
    
        upstream webtools-go-api {
            server webtools-go-api:80;
        }
    
        server {
            listen       80 default_server;
            server_name _;
    
            location /_chk {
                empty_gif;
                access_log off;
                break;
            }
        }
    
        server {
            listen 80;
    
            server_name nanananakam.com;
    
            location /_nuxt/ {
                if ($http_x_forwarded_proto = http) {
                    return 301 https://$host$request_uri;
                }
    
                proxy_pass         http://webtools-front;
                proxy_redirect     off;
            }
    
            location /api/ {
                if ($http_x_forwarded_proto = http) {
                    return 301 https://$host$request_uri;
                }
    
                add_header Cache-Control "no-cache, no-store, max-age=0, must-revalidate" always;
    
                rewrite /api/(.*) /$1  break;
                proxy_pass        http://webtools-go-api;
                proxy_redirect    default;
            }
    
            location / {
                if ($http_x_forwarded_proto = http) {
                    return 301 https://$host$request_uri;
                }
    
                add_header Cache-Control "no-cache, no-store, max-age=0, must-revalidate" always;
                rewrite  ^([^.]*[^/])$ $1/ permanent;
    
                proxy_pass         http://webtools-front;
                proxy_redirect     off;
            }
        }

        server {
            listen 80;

            server_name www.nanananakam.com;
    
            location /_nuxt/ {
                if ($http_x_forwarded_proto = http) {
                    return 301 https://$host$request_uri;
                }
    
                proxy_pass         http://webtools-front;
                proxy_redirect     off;
            }
    
            location /api/ {
                if ($http_x_forwarded_proto = http) {
                    return 301 https://$host$request_uri;
                }
    
                add_header Cache-Control "no-cache, no-store, max-age=0, must-revalidate" always;
    
                rewrite /api/(.*) /$1  break;
                proxy_pass        http://webtools-go-api;
                proxy_redirect    default;
            }
    
            location / {
                if ($http_x_forwarded_proto = http) {
                    return 301 https://$host$request_uri;
                }
    
                add_header Cache-Control "no-cache, no-store, max-age=0, must-revalidate" always;
                rewrite  ^([^.]*[^/])$ $1/ permanent;
    
                proxy_pass         http://webtools-front;
                proxy_redirect     off;
            }
        }
    
        server {
            listen 80;

            server_name api.nanananakam.com;
    
            location / {
                if ($http_x_forwarded_proto = http) {
                    return 301 https://$host$request_uri;
                }
    
                add_header Cache-Control "no-cache, no-store, max-age=0, must-revalidate" always;
    
                proxy_pass         http://webtools-go-api;
                proxy_redirect     off;
            }
        }
    
    }
