apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
data:
  nginx.conf: |-
    user  nginx;

    worker_processes 1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }        

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  30;


        upstream webtools-front {
                server webtools-front:8080;
        }

        server {
            listen 80;

            location / {
                proxy_pass         http://webtools-front;
                proxy_redirect     off;
            }
        }
    }
