apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtools-go-api
spec:
  selector:
    matchLabels:
      app: webtools-go-api
  replicas: 2
  template:
    metadata:
      labels:
        app: webtools-go-api
    spec:
      containers:
        - name: webtools-go-api
          image: kix.ocir.io/ax0w66dqmxlm/webtools-go-api
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: recaptcha-secret
            - secretRef:
                name: object-storage-s3-auth
          startupProbe:
            httpGet:
              path: /_chk
              port: 80
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /_chk
              port: 80
            failureThreshold: 1
            periodSeconds: 10
      imagePullSecrets:
        - name: ocisecret
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - webtools-go-api
                topologyKey: kubernetes.io/hostname
