apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtools-front
spec:
  selector:
    matchLabels:
      app: webtools-front
  replicas: 2
  template:
    metadata:
      labels:
        app: webtools-front
    spec:
      containers:
      - name: webtools-front
        image: kix.ocir.io/ax0w66dqmxlm/webtools
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          failureThreshold: 1
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3000
          failureThreshold: 1
          periodSeconds: 10
      imagePullSecrets:
        - name: ocisecret
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - webtools-front
              topologyKey: kubernetes.io/hostname
